#!/bin/bash

go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

protoc -I=./ --go_out=./conversion --go_opt=paths=source_relative --go-grpc_out=./conversion --go-grpc_opt=paths=source_relative ./conversion.proto

